apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: singletone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: singletone-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "singletone"
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "password123"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: singletone
spec:
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer